import json
import os
from openai import AzureOpenAI, OpenAI
from dotenv import load_dotenv

load_dotenv()

EXTRACTION_SCHEMA = {
    "company_name": "string",
    "filing_type": "10-K or 10-Q",
    "fiscal_year": "YYYY",
    "revenue_current": "number in millions USD or null",
    "revenue_prior": "number in millions USD or null",
    "net_income_current": "number in millions USD or null",
    "net_income_prior": "number in millions USD or null",
    "eps_basic": "number or null",
    "eps_diluted": "number or null",
    "ebitda": "number in millions USD or null",
    "total_debt": "number in millions USD or null",
    "total_equity": "number in millions USD or null",
    "operating_cash_flow": "number in millions USD or null",
    "audit_opinion": "Unqualified / Qualified / Adverse / Going Concern / Disclaimer or null",
    "auditor_name": "string or null",
}


def _get_client():
    if os.getenv("USE_GITHUB_MODELS", "false").lower() == "true":
        return OpenAI(
            base_url="https://models.inference.ai.azure.com",
            api_key=os.getenv("GITHUB_TOKEN"),
        ), os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")
    return AzureOpenAI(
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_key=os.getenv("AZURE_OPENAI_KEY"),
        api_version="2024-08-01-preview",
    ), os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")


# Primary anchors: actual financial statement section headers
_PRIMARY_ANCHORS = [
    "consolidated statements of operations",
    "consolidated statements of income",
    "consolidated statements of earnings",
    "consolidated statement of operations",
    "consolidated statement of income",
]

# Secondary anchors used only if no primary found
_SECONDARY_ANCHORS = [
    "consolidated balance sheet",
    "total net sales",
    "total revenues",
    "net revenues",
]


def _find_anchor(lower: str, markers: list[str], start_from: int = 0) -> int:
    """Return the position of the first matching marker at or after start_from, or -1."""
    for m in markers:
        idx = lower.find(m, start_from)
        if idx != -1:
            return idx
    return -1


def _build_chunk(text: str) -> str:
    """
    Search the second half of the document for the financial statement table
    (actual tables come after the MD&A narrative). Extract a 14 000-char window
    to stay within GitHub Models' 8 000-token limit.
    Header is trimmed to 1 500 chars — just enough for company/filing metadata.
    """
    lower = text.lower()
    midpoint = len(text) // 2
    header = text[:1500]

    # Search second half first — actual financial tables are after the MD&A narrative
    anchor = _find_anchor(lower, _PRIMARY_ANCHORS, start_from=midpoint)
    if anchor == -1:
        anchor = _find_anchor(lower, _PRIMARY_ANCHORS)          # retry full doc
    if anchor == -1:
        anchor = _find_anchor(lower, _SECONDARY_ANCHORS, start_from=midpoint)
    if anchor == -1:
        anchor = _find_anchor(lower, _SECONDARY_ANCHORS)
    if anchor == -1:
        return header + "\n...[middle omitted]...\n" + text[-12000:]

    start = max(0, anchor - 300)
    financial_section = text[start: start + 14000]
    return header + "\n...\n" + financial_section


def extract_metrics(filing_text: str) -> dict:
    """
    Extract structured financial metrics from an SEC filing using GPT-4o.
    Targets the financial statement sections rather than head/tail.
    """
    client, model = _get_client()
    chunk = _build_chunk(filing_text)

    prompt = f"""You are a financial analyst extracting data from an SEC 10-K or 10-Q filing.
Extract the metrics below from the filing text. Numbers are often in thousands or millions — \
check the filing header or table notes for the unit scale and convert everything to millions of USD.

Return ONLY valid JSON matching this schema (use null for genuinely missing values, never guess):
{json.dumps(EXTRACTION_SCHEMA, indent=2)}

Rules:
- revenue_current / revenue_prior: total net sales or total revenues for the most recent and prior fiscal year
- net_income_current / net_income_prior: net income (or net earnings) for current and prior year
- ebitda: operating income + depreciation & amortization if stated, else null
- total_debt: long-term debt + current portion of long-term debt
- total_equity: total shareholders equity (or stockholders equity)
- eps_basic / eps_diluted: from the EPS table, most recent year
- operating_cash_flow: net cash generated by / used in operating activities
- audit_opinion: from the auditor's report section — Unqualified means clean/no issues
- auditor_name: the name of the external auditing firm

FILING TEXT:
{chunk}
"""

    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"},
        temperature=0,
    )

    return json.loads(response.choices[0].message.content)
